export const WS_MSGS = {
    ADD_SHIPS: 'add_ships',
    ADD_USER_TO_ROOM: 'add_user_to_room',
    ATTACK: 'attack',
    CREATE_GAME: 'create_game',
    CREATE_ROOM: 'create_room',
    FINISH: 'finish',
    KILLED: 'killed',
    MISS: 'miss',
    RANDOM_ATTACK: 'randomAttack',
    REG: 'reg',
    SHOT: 'shot',
    START_GAME: 'start_game',
    TURN: 'turn',
    UPDATE_ROOM: 'update_room',
    UPDATE_WINNERS: 'update_winners',
};
